import { useState } from 'react'
import { ResultsGrid } from './components/ResultsGrid'
import { ScanConsole } from './components/ScanConsole'
import { TerminalWindow } from './components/TerminalWindow'
import { useReconScan } from './hooks/useReconScan'
import type { StartScanInput } from './types/recon'
import './App.css'

const navigation = [{ label: 'Overview', icon: '⌂' }, { label: 'Scans', icon: '◌' }, { label: 'Targets', icon: '◎' }, { label: 'Settings', icon: '⚙' }]

function App() {
  const { scan, isLoading, isStarting, startScan } = useReconScan()
  const [activeNav, setActiveNav] = useState('Overview')
  const [terminalOpen, setTerminalOpen] = useState(true)
  const handleStart = (input: StartScanInput) => startScan(input)
  const activeCount = scan?.modules.filter((module) => module.enabled && module.status === 'running').length ?? 0
  if (isLoading || !scan) return <div className="loading-screen"><span className="pulse-dot" /> Connecting to recon workspace...</div>
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">Q</span><span>qyburn<span className="brand-accent">.os</span></span></div><div className="workspace-switcher"><span className="workspace-avatar">A</span><span><small>Workspace</small>Acme Security</span><span className="chevron">⌄</span></div><nav className="main-nav" aria-label="Main navigation">{navigation.map((item) => <button type="button" key={item.label} className={activeNav === item.label ? 'active' : ''} onClick={() => setActiveNav(item.label)}><span>{item.icon}</span>{item.label}{item.label === 'Scans' && <b>{activeCount || 1}</b>}</button>)}</nav><div className="sidebar-bottom"><div className="connection"><span className="pulse-dot" /><span><small>API connection</small>Operational</span><strong>•••</strong></div><div className="user-row"><span className="user-avatar">JD</span><span><strong>Jordan Davis</strong><small>Security analyst</small></span><span className="more">•••</span></div></div></aside>
    <main className="main-content"><header className="topbar"><div><span className="breadcrumb">Workspace / <b>{activeNav}</b></span><span className="live-badge"><span className="pulse-dot" /> 3 active scans</span></div><div className="top-actions"><button type="button" className="top-icon" aria-label="Search">⌕</button><button type="button" className="top-icon" aria-label="Notifications">♧<i /></button><span className="top-date">SEP 11, 2026</span></div></header><div className="content-wrap"><div className="page-intro"><div><p className="eyebrow">THURSDAY, SEPTEMBER 11 <span>·</span> 09:44 UTC</p><h2>Good morning, Jordan.</h2></div><button className="history-button" type="button">↺ <span>Scan history</span><b>24</b></button></div><ScanConsole onStart={handleStart} disabled={isStarting || scan.status === 'running'} /><section className="metrics-row"><div className="metric-card"><span>Open ports</span><strong>{scan.summary.openPorts}</strong><small className="positive">↑ 12% <i>vs last scan</i></small><div className="mini-bars">{[24, 39, 28, 52, 42, 72, 65, 88, 76].map((height, index) => <i key={index} style={{ height: `${height}%` }} />)}</div></div><div className="metric-card"><span>Live subdomains</span><strong>{scan.summary.liveSubdomains}</strong><small className="positive">↑ 4 <i>vs last scan</i></small><div className="sparkline"><svg viewBox="0 0 120 30" role="img" aria-label="Subdomain growth trend"><polyline points="0,25 15,20 28,22 44,13 57,16 72,8 90,11 106,4 120,6" /></svg></div></div><div className="metric-card warning-card"><span>Vulnerabilities</span><strong>{scan.summary.vulnerabilities}</strong><small className="negative">↑ 1 <i>needs attention</i></small><div className="risk-level"><span>Risk level</span><b>Moderate</b><i><em /></i></div></div><div className="metric-card"><span>Scan duration</span><strong>{scan.duration}</strong><small className="neutral">Last completed scan</small><div className="duration-line"><span style={{ width: `${scan.progress}%` }} /></div></div></section><div className="results-heading"><div><span className="section-kicker">Live results</span><h2>Attack surface <span>· {scan.target.value}</span></h2></div><div className="scan-progress"><span className="scan-state"><i /> {scan.status === 'running' ? 'Scanning' : 'Scan complete'}</span><span>{scan.progress}%</span><div><i style={{ width: `${scan.progress}%` }} /></div></div></div><ResultsGrid results={scan.results} /><button type="button" className="terminal-toggle" onClick={() => setTerminalOpen((open) => !open)}><span>⌁</span> {terminalOpen ? 'Hide' : 'Show'} terminal <i>{terminalOpen ? '⌄' : '⌃'}</i></button>{terminalOpen && <TerminalWindow />}</div></main>
  </div>
}
export default App
